triage:
  rules:
  - labels: [area/persistence]
    title: "(?i).*persistence.*"
    body: "(?i).*persistence.*"
    notify: [gsmet]
  - labels: [area/validator]
    title: "(?i).*validator.*"
    body: "(?si).*validator.*"
    notify: [gsmet]
